export const INGREDIENT_CATEGORIES = {
  proteins: {
    label: "Proteins",
    items: [
      "Chicken",
      "Beef",
      "Pork",
      "Lamb",
      "Turkey",
      "Salmon",
      "Tuna",
      "Shrimp",
      "Cod",
      "Eggs",
      "Tofu",
      "Bacon",
      "Sausage",
    ],
  },
  vegetables: {
    label: "Vegetables",
    items: [
      "Onion",
      "Garlic",
      "Tomato",
      "Potato",
      "Carrot",
      "Broccoli",
      "Spinach",
      "Mushrooms",
      "Bell Pepper",
      "Zucchini",
      "Celery",
      "Corn",
      "Peas",
      "Green Beans",
      "Lettuce",
      "Cucumber",
      "Avocado",
      "Eggplant",
    ],
  },
  dairy: {
    label: "Dairy",
    items: [
      "Milk",
      "Butter",
      "Cheese",
      "Cream",
      "Parmesan",
      "Mozzarella",
      "Cream Cheese",
      "Yogurt",
      "Sour Cream",
    ],
  },
  grains: {
    label: "Grains & Pasta",
    items: [
      "Rice",
      "Pasta",
      "Bread",
      "Flour",
      "Noodles",
      "Tortillas",
      "Oats",
      "Couscous",
    ],
  },
  spices: {
    label: "Spices & Herbs",
    items: [
      "Salt",
      "Pepper",
      "Paprika",
      "Cumin",
      "Oregano",
      "Basil",
      "Thyme",
      "Rosemary",
      "Cinnamon",
      "Chili Powder",
      "Ginger",
      "Turmeric",
      "Parsley",
      "Cilantro",
    ],
  },
  pantry: {
    label: "Pantry",
    items: [
      "Olive Oil",
      "Vegetable Oil",
      "Soy Sauce",
      "Vinegar",
      "Sugar",
      "Honey",
      "Lemon",
      "Lime",
      "Coconut Milk",
      "Tomato Sauce",
      "Chicken Stock",
      "Beans",
      "Lentils",
      "Chickpeas",
    ],
  },
} as const;

export const COCKTAIL_INGREDIENT_CATEGORIES = {
  spirits: {
    label: "Spirits",
    items: [
      "Vodka",
      "Gin",
      "Rum",
      "Tequila",
      "Whiskey",
      "Bourbon",
      "Scotch",
      "Brandy",
      "Cognac",
      "Mezcal",
    ],
  },
  liqueurs: {
    label: "Liqueurs",
    items: [
      "Triple Sec",
      "Kahlua",
      "Amaretto",
      "Baileys",
      "Campari",
      "Aperol",
      "Cointreau",
      "Grand Marnier",
      "Chambord",
      "Maraschino Liqueur",
      "Blue Curacao",
    ],
  },
  mixers: {
    label: "Mixers",
    items: [
      "Tonic Water",
      "Soda Water",
      "Cola",
      "Ginger Beer",
      "Ginger Ale",
      "Orange Juice",
      "Cranberry Juice",
      "Pineapple Juice",
      "Tomato Juice",
      "Coconut Cream",
      "Cream",
      "Milk",
    ],
  },
  fresh: {
    label: "Fresh & Garnish",
    items: [
      "Lemon",
      "Lime",
      "Orange",
      "Mint",
      "Sugar",
      "Egg White",
      "Grenadine",
      "Bitters",
      "Angostura Bitters",
      "Simple Syrup",
      "Honey",
      "Ice",
    ],
  },
  wine: {
    label: "Wine & Vermouth",
    items: [
      "Red Wine",
      "White Wine",
      "Champagne",
      "Prosecco",
      "Dry Vermouth",
      "Sweet Vermouth",
    ],
  },
} as const;

export const STALE_TIME = 1000 * 60 * 30;
